require 'quo_vadis/engine'

module QuoVadis

  #
  # Configuration
  #

  mattr_accessor :signed_in_url
  @@signed_in_url = :root

  def self.signed_in_url(user)
    @@signed_in_url.respond_to?(:call) ?  @@signed_in_url.call(user) : @@signed_in_url
  end


  mattr_accessor :signed_out_url
  @@signed_in_url = :root


  # Configure from the initializer (generated by generator).
  def self.configure
    yield self
  end

end
