require 'quo_vadis/engine'

module QuoVadis

  #
  # Configuration
  #

  #
  mattr_accessor :signed_in_url
  @@signed_in_url = :root

  def self.signed_in_url(user)
    @@signed_in_url.respond_to?(:call) ?  @@signed_in_url.call(user) : @@signed_in_url
  end

  #
  mattr_accessor :signed_out_url
  @@signed_in_url = :root

  #
  mattr_accessor :signed_in_hook
  @@signed_in_hook = nil

  def self.signed_in_hook(user, request)
    @@signed_in_hook.call(user, request) if @@signed_in_hook
  end


  # Configure from the initializer (generated by generator).
  def self.configure
    yield self
  end

end
